namespace Electronic_Bank.Models
{
    public class Currency
    {
        public int CurrencyID { get; set; }
        public double CurrencyPrice { get; set; }
        public String CurrencyName { get; set; }
        public String CurrencyCode { get; set; }

        public virtual ICollection<Wallet> CurrencyWallets { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    }
}
